extend type Album {
  """
  ✨ Implicit foreign key field based on `Album`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: String! @fdc_generated(from: "Album.user", purpose: IMPLICIT_REF_FIELD)
}
extend type Photo {
  """
  ✨ Implicit foreign key field based on `Photo`.`album`. It must match the value of `Album`.`id`. See `@ref` for how to customize it.
  """
  albumId: UUID! @fdc_generated(from: "Photo.album", purpose: IMPLICIT_REF_FIELD)
}
