extend type Query {
  """
  ✨ Look up a single `Album` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  album(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Album_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Album_FirstRow
  ): Album @fdc_generated(from: "Album", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Photo` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  photo(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Photo_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Photo_FirstRow
  ): Photo @fdc_generated(from: "Photo", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `User` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  user(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow
  ): User @fdc_generated(from: "User", purpose: QUERY_SINGLE)
  """
  ✨ List `Album` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  albums(
    """
    Filter condition to narrow down the query results.
    """
    where: Album_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Album_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Album_Having
  ): [Album!]! @fdc_generated(from: "Album", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Photo` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  photos(
    """
    Filter condition to narrow down the query results.
    """
    where: Photo_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Photo_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Photo_Having
  ): [Photo!]! @fdc_generated(from: "Photo", purpose: QUERY_MULTIPLE)
  """
  ✨ List `User` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  users(
    """
    Filter condition to narrow down the query results.
    """
    where: User_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [User_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: User_Having
  ): [User!]! @fdc_generated(from: "User", purpose: QUERY_MULTIPLE)
}
