extend type Album {
  """
  ✨ List `Photo` objects in a one-to-many relationship (where `Photo`.`album` is this object).
  """
  photos_on_album(
    """
    Filter condition to narrow down the query results.
    """
    where: Photo_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Photo_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Photo_Having
  ): [Photo!]! @fdc_generated(from: "Photo.album", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Album", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Album` table.
  """
  _count: Int! @fdc_generated(from: "Album.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Album` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Album.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Album` table where the `description` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  description_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Album.description", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Album` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Album.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Album` table where the `title` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  title_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Album.title", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Album` table where the `userId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  userId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Album.userId", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `createdAt` field in the `Album` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "Album.createdAt", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `Album` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "Album.createdAt", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Album.id", purpose: GLOBAL_ID)
}
extend type Photo {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Photo", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Photo` table.
  """
  _count: Int! @fdc_generated(from: "Photo.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Photo` table where the `addedAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  addedAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Photo.addedAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Photo` table where the `albumId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  albumId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Photo.albumId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Photo` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Photo.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Photo` table where the `photoUrl` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  photoUrl_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Photo.photoUrl", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `addedAt` field in the `Photo` table.
  """
  addedAt_min: Timestamp @fdc_generated(from: "Photo.addedAt", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `addedAt` field in the `Photo` table.
  """
  addedAt_max: Timestamp @fdc_generated(from: "Photo.addedAt", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Photo.id", purpose: GLOBAL_ID)
}
extend type User {
  """
  ✨ List `Album` objects in a one-to-many relationship (where `Album`.`user` is this object).
  """
  albums_on_user(
    """
    Filter condition to narrow down the query results.
    """
    where: Album_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Album_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Album_Having
  ): [Album!]! @fdc_generated(from: "Album.user", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "User", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `User` table.
  """
  _count: Int! @fdc_generated(from: "User.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `email` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  email_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.email", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `username` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  username_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.username", purpose: QUERY_COUNT)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "User.id", purpose: GLOBAL_ID)
}
