type User @table {
  id: String! @col(name: "uid") @default(expr: "auth.uid")
  email: String!
  username: String
}

type Album @table {
  id: UUID! @default(expr: "uuidV4()")
  title: String!
  description: String
  createdAt: Timestamp! @default(expr: "request.time")
  user: User!
}

type Photo @table {
  id: UUID! @default(expr: "uuidV4()")
  photoUrl: String!
  addedAt: Timestamp! @default(expr: "request.time")
  album: Album!
}